import Navbar from '@/components/Navbar'
import './globals.css'
import { Poppins } from 'next/font/google'

const pop = Poppins({ subsets: ['latin'], weight: ['200', '400', '500', '600', '700', '800'] })

export const metadata = {
  title: 'yasersyafaa',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='' id='html'>
      <body className={`bg-[#68242a] text-[#FFC5C3] dark:text-[#68242a] dark:bg-[#FFC5C3] duration-100 ${pop.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
